"use client";

import { useEffect, useMemo, useState } from "react";

type Section = { id: string; sectionType: string; content: Record<string, unknown>; isVisible: boolean; sectionOrder: number };
const labels: Record<string, string> = { HEADER: "Header", HERO: "Hero banner", FEATURED_PRODUCTS: "Featured products", PROMO_BANNER: "Promo banner", ABOUT: "About us", FOOTER: "Footer" };

export default function WebsiteEditorPage() {
  const [sections, setSections] = useState<Section[] | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const current = useMemo(() => sections?.find((section) => section.id === selected) ?? null, [sections, selected]);
  const sorted = useMemo(() => sections ? [...sections].sort((a, b) => a.sectionOrder - b.sectionOrder) : [], [sections]);

  useEffect(() => { fetch("/api/sections").then((r) => r.json()).then((data) => { const items = Array.isArray(data) ? data : []; setSections(items); setSelected(items[0]?.id ?? null); }); }, []);
  async function patch(section: Section, data: Record<string, unknown>) { setSaving(true); try { const response = await fetch(`/api/sections/${section.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const updated = await response.json(); if (response.ok) setSections((previous) => previous!.map((item) => item.id === section.id ? updated : item)); } finally { setSaving(false); } }
  async function move(section: Section, direction: "up" | "down") { const response = await fetch("/api/sections/reorder", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sectionId: section.id, direction }) }); if (!response.ok) return; const result = await response.json(); setSections((previous) => previous!.map((item) => item.id === result.sourceId ? { ...item, sectionOrder: result.sourceOrder } : item.id === result.targetId ? { ...item, sectionOrder: result.targetOrder } : item)); }

  if (!sections) return <div className="grid min-h-[70vh] place-items-center text-slate-500">Loading design studio…</div>;
  return <div className="-m-5 min-h-screen md:-m-10"><header className="border-b bg-white px-5 py-4 md:px-8"><p className="text-sm font-semibold uppercase tracking-[.18em] text-forge">Design studio</p><div className="mt-1 flex items-center justify-between gap-4"><div><h1 className="font-display text-2xl font-semibold">Shape your storefront</h1><p className="text-sm text-slate-600">Changes are saved when you apply them.</p></div><span className="text-sm text-slate-500">{saving ? "Saving…" : "Saved"}</span></div></header><div className="grid min-h-[calc(100vh-112px)] lg:grid-cols-[260px_minmax(0,1fr)_370px]">
    <aside className="border-r bg-white p-5"><h2 className="font-display text-lg font-semibold">Page sections</h2><div className="mt-5 space-y-2">{sorted.map((section, index) => <div key={section.id} className={`rounded-lg border p-3 ${section.id === selected ? "border-forge bg-forge/5" : "bg-slate-50"}`}><button onClick={() => setSelected(section.id)} className="flex w-full items-center justify-between text-left"><span className={!section.isVisible ? "text-slate-400 line-through" : "font-medium"}>{labels[section.sectionType] ?? section.sectionType}</span><span className="text-xs text-slate-500">{section.isVisible ? "Visible" : "Hidden"}</span></button>{section.id === selected && <div className="mt-3 flex gap-2"><button disabled={index === 0} onClick={() => move(section, "up")} className="forge-button-secondary px-3 py-1 text-sm">↑</button><button disabled={index === sorted.length - 1} onClick={() => move(section, "down")} className="forge-button-secondary px-3 py-1 text-sm">↓</button><button onClick={() => patch(section, { isVisible: !section.isVisible })} className="forge-button-secondary flex-1 py-1 text-sm">{section.isVisible ? "Hide" : "Show"}</button></div>}</div>)}</div></aside>
    <main className="bg-slate-100 p-5 md:p-8"><p className="mb-3 text-sm font-medium text-slate-500">Live-style preview</p><Preview section={current} /></main>
    <aside className="border-l bg-white p-5 md:p-7">{current ? <SectionForm key={current.id} section={current} onApply={(content) => patch(current, { content })} saving={saving} /> : <p>Select a section to design it.</p>}</aside>
  </div></div>;
}

function Preview({ section }: { section: Section | null }) {
  if (!section) return <div className="grid min-h-[420px] place-items-center rounded-xl bg-white text-slate-500">Select a section to preview it.</div>;
  const c = section.content as Record<string, string>;
  return <div className="min-h-[520px] overflow-hidden rounded-xl bg-white shadow-forge"><div className="border-b px-6 py-4 font-display font-semibold">{c.logoText || "Your store"}</div>{section.sectionType === "HERO" ? <div className="min-h-[360px] bg-slate-800 bg-cover bg-center p-10 text-white" style={c.image ? { backgroundImage: `linear-gradient(90deg, rgba(15,23,42,.75), rgba(15,23,42,.2)), url(${c.image})` } : undefined}><p className="text-sm uppercase tracking-[.2em] text-forge-light">Your brand</p><h2 className="mt-5 max-w-xl font-display text-5xl font-bold">{c.heading || "Your headline"}</h2><p className="mt-4 max-w-md">{c.description}</p><button className="mt-7 rounded bg-forge px-5 py-3 text-sm font-semibold">{c.buttonText || "Shop now"}</button></div> : <div className="p-10"><p className="text-sm uppercase tracking-[.2em] text-forge">{labels[section.sectionType]}</p><h2 className="mt-4 font-display text-4xl font-bold">{c.heading || c.logoText || "Your content"}</h2><p className="mt-4 max-w-xl leading-7 text-slate-600">{c.body || c.description || c.text || "Use the controls to make this section sound like your business."}</p></div>}</div>;
}

function SectionForm({ section, onApply, saving }: { section: Section; onApply: (content: Record<string, string>) => void; saving: boolean }) {
  const initial = section.content as Record<string, string>; const [content, setContent] = useState<Record<string, string>>({ ...initial });
  const fields: Record<string, Array<[string, string, boolean]>> = { HEADER: [["logoText", "Store name in header", false]], HERO: [["heading", "Headline", false], ["description", "Supporting text", true], ["buttonText", "Button label", false], ["buttonLink", "Button link (for example #shop)", false], ["image", "Hero image URL", false]], FEATURED_PRODUCTS: [["heading", "Section heading", false]], PROMO_BANNER: [["heading", "Promotion text", false], ["link", "Promotion link", false]], ABOUT: [["heading", "Section heading", false], ["body", "Your story", true]], FOOTER: [["text", "Footer text", true]] };
  return <><p className="text-sm font-semibold uppercase tracking-[.18em] text-forge">Editing</p><h2 className="mt-2 font-display text-2xl font-semibold">{labels[section.sectionType]}</h2><p className="mt-2 text-sm leading-6 text-slate-600">Use plain language that tells customers what to expect.</p><div className="mt-6 space-y-4">{(fields[section.sectionType] ?? []).map(([name, label, multiline]) => <label key={name} className="block text-sm font-medium text-slate-700">{label}{multiline ? <textarea className="input mt-1 w-full" rows={4} value={content[name] ?? ""} onChange={(e) => setContent({ ...content, [name]: e.target.value })} /> : <input className="input mt-1 w-full" value={content[name] ?? ""} onChange={(e) => setContent({ ...content, [name]: e.target.value })} />}</label>)}</div><button disabled={saving} onClick={() => onApply(content)} className="forge-button mt-6 w-full">{saving ? "Saving…" : "Apply changes"}</button></>;
}
